### File Upload (multipart)
POST https://localhost:9999/multipart.create
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="book.pdf"
Content-Type: book.pdf

< ./book.pdf
--WebAppBoundary--

### Task status
GET https://localhost:9999/tasks.getById?id=341fbb60-aab3-46f2-aab3-bb72b7289132
Authorization: Bearer {{token}}

### All tasks status By User
GET https://localhost:9999/tasks.getAllByUserId
Authorization: Bearer {{token}}

### Get Zip-archive
GET https://localhost:9999/tasks.getResultById?id=341fbb60-aab3-46f2-aab3-bb72b7289132
Authorization: Bearer {{token}}

### Get All Tasks of Users by Admin
GET https://localhost:9999/tasks.getAll

### Admin Get Tasks by User Id
GET https://localhost:9999/tasks.getTaskByAdmin?id=4

### Admin Download File by User Id
GET https://localhost:9999/tasks.getFileById?id=d3f8e1e4-275a-4355-9117-85ea8e3d9f32

### Добавить реквесты на файлы с разными расширениями

