### File Upload (multipart)
POST https://localhost:9999/multipart.create
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="book.pdf"
Content-Type: book.pdf

< ./book.pdf
--WebAppBoundary--

### Task status
GET https://localhost:9999/tasks.getById?id=9e8cd224-6821-438c-9a89-ecc1e7f4af61
Authorization: Bearer {{token}}

### All tasks status By User
GET https://localhost:9999/tasks.getAllByUserId
Authorization: Bearer {{token}}

### Get Zip-archive
GET https://localhost:9999/tasks.getResultById?id=9e8cd224-6821-438c-9a89-ecc1e7f4af61
Authorization: Bearer {{token}}

### Get All Tasks of Users by Admin
GET https://localhost:9999/tasks.getAll

### Admin Get Tasks by User Id
GET https://localhost:9999/tasks.getTaskByAdmin?id=4

### Admin Download File by User Id
GET https://localhost:9999/tasks.getFileById?id=9e8cd224-6821-438c-9a89-ecc1e7f4af61

